// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: validator.proto

package validatorproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ValidatorsClient is the client API for Validators service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidatorsClient interface {
	GetValidators(ctx context.Context, in *ValidatorsRequest, opts ...grpc.CallOption) (*ValidatorsResponse, error)
}

type validatorsClient struct {
	cc grpc.ClientConnInterface
}

func NewValidatorsClient(cc grpc.ClientConnInterface) ValidatorsClient {
	return &validatorsClient{cc}
}

func (c *validatorsClient) GetValidators(ctx context.Context, in *ValidatorsRequest, opts ...grpc.CallOption) (*ValidatorsResponse, error) {
	out := new(ValidatorsResponse)
	err := c.cc.Invoke(ctx, "/validatorproto.Validators/GetValidators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidatorsServer is the server API for Validators service.
// All implementations must embed UnimplementedValidatorsServer
// for forward compatibility
type ValidatorsServer interface {
	GetValidators(context.Context, *ValidatorsRequest) (*ValidatorsResponse, error)
	mustEmbedUnimplementedValidatorsServer()
}

// UnimplementedValidatorsServer must be embedded to have forward compatible implementations.
type UnimplementedValidatorsServer struct {
}

func (UnimplementedValidatorsServer) GetValidators(context.Context, *ValidatorsRequest) (*ValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidators not implemented")
}
func (UnimplementedValidatorsServer) mustEmbedUnimplementedValidatorsServer() {}

// UnsafeValidatorsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidatorsServer will
// result in compilation errors.
type UnsafeValidatorsServer interface {
	mustEmbedUnimplementedValidatorsServer()
}

func RegisterValidatorsServer(s grpc.ServiceRegistrar, srv ValidatorsServer) {
	s.RegisterService(&Validators_ServiceDesc, srv)
}

func _Validators_GetValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorsServer).GetValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/validatorproto.Validators/GetValidators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorsServer).GetValidators(ctx, req.(*ValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Validators_ServiceDesc is the grpc.ServiceDesc for Validators service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Validators_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "validatorproto.Validators",
	HandlerType: (*ValidatorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValidators",
			Handler:    _Validators_GetValidators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "validator.proto",
}
